name: Development tests
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  test:
    name: Tests without emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3

      - name: Check
        run: ./gradlew lib:check

  test_on_emulator:
    name: Tests with emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Cache AVD
        uses: actions/cache@v4
        with:
          path: ~/.config/.android/avd
          key: avd-${{ hashFiles('lib/build.gradle.kts') }}   # gradle-managed devices are defined there

      - name: Run device tests
        run: ./gradlew --no-daemon lib:virtualCheck
